---
- name: Snapd_running
  when: not ansible_check_mode
  become: true
  ansible.builtin.service:
    state: started
    enabled: true
    name: snapd

- name: Reload_sysctl
  when: not ansible_check_mode
  become: true
  ansible.builtin.command: sysctl --system
  changed_when: true
