---
# paths
local_config_dir: "~/.config/git"
local_config_user_name_config: "{{ local_config_dir }}/user-name.local"
local_config_gpg_key_config: "{{ local_config_dir }}/gpg-key.local"
local_config_github_credential_config: "{{ local_config_dir }}/github-credential.local"
